# Generated by Django 4.2.1 on 2023-10-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="menu_name",
            field=models.CharField(default="main_menu", max_length=50),
        ),
    ]
