# Generated by Django 4.2.1 on 2023-10-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu_app", "0003_alter_menuitem_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="menu_name",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="named_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="menu_app.menuitem",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
