# Generated by Django 4.2.1 on 2023-10-06 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "menu_app",
            "0004_rename_title_menuitem_name_remove_menuitem_menu_name_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="named_url",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="menu_name",
            field=models.CharField(default="main_menu", max_length=50),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="menu_app.menuitem",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="url",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
