# Generated by Django 4.2.1 on 2023-10-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_app", "0006_rename_title_menuitem_name_remove_menuitem_menu_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
